name: developing-with-qiime2
channels:
- https://packages.qiime2.org/qiime2/2025.7/tiny/passed
- conda-forge
- bioconda
dependencies:
  - qiime2-tiny
  - pip
  - pip:
    - jupyter-book
    - sphinxcontrib-mermaid
    - q2doc @ git+https://github.com/qiime2/sphinx-ext-qiime2.git@master